project:
  type: website
  output-dir: docs # <-- For setting on Github

  preview: 
    port: 2810
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 3600

# Freeze code execution locally prior to deployment to CI server
execute:
  freeze: auto

# Website settings
website:
  title: "Chaance T. Graves"
  #site-url:
  description: "My personal blog about engineering projects"
  #site-url:
  #repo-url:
  favicon: assets/img/favicon.png
  navbar:
    collapse: false
    tools:
      - icon: github
        href: https://github.com/ctg123
      - icon: linkedin
        href: https://linkedin.com/in/chaancegraves

    left:
      #- href: index.qmd
      #  text: About

      - href: resume.qmd
        text: Resume

      - href: blog.qmd
        text: Blog

      - href: projects.qmd
        text: Projects
  # page footer settings
  page-footer: 
    border: true
    left: "&#169; 2024 Chaance T. Graves | Made with [Quarto](https://quarto.org)"  
    right:
      - text: License
        href: license.qmd

# Formatting the website appearance
format:
  html:
    theme: simplex
    css: styles.css
    toc: true



