project:
  type: website
  output-dir: docs # <-- For setting on Github

  preview: 
    port: 2810
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 3600

# Freeze code execution locally prior to deployment to CI server
execute:
  freeze: auto

# Website settings
website:
  title: "Chaance T. Graves"
  description: "My personal blog about engineering projects"
  #site-url:
  favicon: assets/img/favicon.png
  #repo-url:
  #repo-actions:
  #search: true

  navbar:
    collapse: false
    tools:
      - icon: github
        href: https://github.com/ctg123
      - icon: linkedin
        href: https://linkedin.com/in/chaancegraves

    left:
      - text: Home
        icon: house-gear-fill
        href: index.qmd

      - text: Resume
        icon: file-text-fill
        href: resume.qmd

      - text: Blog
        icon: layout-text-sidebar
        href: blog.qmd

      - text: Projects
        icon: kanban
        href: projects.qmd

  # page footer settings
  page-footer: 
    border: true
    left: "&#169; 2024 Chaance T. Graves | Made with [Quarto](https://quarto.org)"  
    right:
      - text: License
        href: license.qmd

# Formatting the website appearance
format:
  html:
    theme: 
      - sandstone
      - styles.scss
    #css: styles.css
    toc: true



