project:
  type: website
  output-dir: docs # <-- final docs published after "quarto render" locally.

  preview: 
    port: 2810
    browser: true
    watch-inputs: true
    navigate: true
    timeout: 3600

# Freeze code execution locally prior to deployment to CI server
execute:
  freeze: auto

# Website settings
website:
  title: "Chaance T. Graves"
  description: "My personal blog about engineering projects"
  #site-url:
  repo-url: https://github.com/ctg123/quarto-example-site
  repo-actions:
    - source
    - issue
  search:
    location: navbar
    type: textbox
  favicon: assets/img/favicon.png
  page-navigation: true
  back-to-top-navigation: true
  #open-graph: 

  navbar:
    pinned: true
    #logo: 
    #logo-alt: 
    collapse: true
    tools:
      #- icon: envelope-check
      #  href: mailto:chaance.graves@ctginnovations.io

      - icon: github
        href: https://github.com/ctg123
        
      - icon: linkedin
        href: https://linkedin.com/in/chaancegraves

    left:
      - text: "{{< fa house-user >}} Home"
        #icon: house-gear-fill
        href: index.qmd

      - text: "{{< fa laptop-code >}} Resume"
        #icon: file-text-fill
        href: https://resume.chaancegraves.com/

      - text: "{{< fa bolt >}} Projects"
        #icon: lightning-charge
        href: projects/index.qmd

      - text: "{{< fa rectangle-list >}} Blog"
        #icon: layout-text-sidebar
        href: blog/index.qmd

      #- text: Notes
      #  icon: journals
      #  href: notes/index.qmd

      - text: "{{< fa paper-plane >}} Contact"
        href: mailto:chaance.graves@ctginnovations.io

  # page footer settings
  page-footer: 
    border: true
    left: "&#169; 2025 Chaance T. Graves | Rendered with [Quarto](https://quarto.org) v{{< version >}}"  
    right:
      - text: License
        href: license/index.qmd

# Formatting the website appearance
format:
  html:
    theme: 
      light: assets/styling/ctg-theme-light.scss
      dark: assets/styling/ctg-theme-dark.scss
    mainfont: Rubik
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    footnotes-hover: true
    highlight-style: monokai
    respect-user-color-scheme: true
    #pagetitle: "{{< meta title >}}"



