---
title: "Are you getting started to learn Python? 🐍"
author: "Chaance Graves"
date: "2021-01-20"
date-modified: "2024-11-30"
categories: [resources, code, python]
image: https://res.cloudinary.com/website-assets-mgmt/image/upload/c_scale,w_500/r_15/f_auto/q_auto/v1/website/blog/python-intro/code-img

format: 
  html:
    toc: true
    toc-title: Contents
    toc-location: right
---

Are you new to programming? Have questions about which language would be a good one to start?

Choosing which programming language to learn is more a personal preference depending on what project and solution you're looking to achieve. However, for a beginner, you have lots of flexibility to experiment with which one is right for you. One programming language I enjoy working with and others have found helpful is Python. I recommend installing [Python 3](https://www.python.org/downloads/) to have more community support to be developed and used for years to come.

There are likely millions of developers worldwide using Python to build projects, tools and using it to teach others the fundamentals of programming. You can do all kinds of other fantastic work in a multitude of domains.

#### Example applications:

* Web applications
* Machine Learning / Deep learning
* Automating weekly emails
* Setting up jobs to update a spreadsheet
* etc.

#### Helpful online resources & books

You can find plentiful resources to teach yourself Python or pair with a small group to work on projects!

[Codeacademy](https://www.codecademy.com/learn/learn-python-3): Codeacademy offers free code tutorials that are very popular for a good reason. The tutorials should give you a good idea of what it's like to code Python with hands-on lessons to write code.

[Learn Python the Hard Way by Zed Shaw](https://learncodethehardway.org/python/):  This book is well received and aims to teach beginners how to read and write basic Python to understand other books on Python. It is high quality which I recommend regardless of where your current skill is. You can try the [free sample](https://learnpythonthehardway.org/python3/) to see if it would work for you.

[Real Python](https://realpython.com/): This website offers in-depth tutorials to learn any aspect of Python you may be curious to explore. Check it out and keep a list of articles for future reference!

[Automate the boring stuff with Python by Al Sweigart](https://automatetheboringstuff.com/): This is an enjoyable read and practical for anyone who is currently working a tedious, routine job! He also offers a video course provided through Udemy.

[Udemy](https://www.udemy.com/topic/python/free/): You can find all sorts of courses and projects offered on this online education website. They range from beginner to advanced and have instructors teaching financial topics such as predicting stock prices, data science, full-stack web development, and more.

I'm confident your programming journey will be well on its way towards success. Feel free to discuss any other valuable resources or projects you've discovered learning Python. 👌🏾
